language: python
python:
  - "3.5"

before_install:
  - sudo apt-get install yasm
  - sudo apt-get install g++-multilib libc6-dev-i386

install:
  - "pip install antlr4-python3-runtime"

script: python ./CompilerTest.py
script: python ./CompilerOptimiztionTest.py